version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_USER: ${mysql_user}
      MYSQL_ROOT_PASSWORD: ${mysql_password}
      MYSQL_PASSWORD: ${mysql_password}
      MYSQL_DATABASE: ${mysql_db}
    healthcheck:
      # healthcheck for checking the mysql container is up before starting my app container
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - '3307:3306'
  web:
    build: .
    image: yossibenga/flask_app
    container_name: flask_app
    depends_on:
    # starting the container only after the mysql container is up and running
      db: 
        condition: service_healthy
    ports:
      - "5000:5000"
    working_dir: ${csv_dir_in_the_container}
    links:
      - db

